vim.g.mapleader = ';'

require("nest").applyKeymaps {
  { "<leader>", {
    { "F", '<cmd>Telescope<CR>' },
    { "f", '<cmd>Telescope find_files<CR>' },
    { "S", '<cmd>Telescope symbols<CR>' },
    { "b", '<cmd>Telescope buffers<CR>' },
    { "/", '<cmd>Telescope live_grep<CR>' },
    { "d", '<cmd>NvimTreeToggle<CR>' },
    { "m", '<cmd>MinimapToggle<CR>' },
    { "c", '<cmd>Telescope commands<CR>' },
    { "n", '<cmd>BufferLineCycleNext<CR>' },
    { "p", '<cmd>BufferLineCyclePrev<CR>' },
    { "g", {
      { "b", '<cmd>Git blame<CR>' },
      { "s", '<cmd>Git status<CR>' },
      { "S", '<cmd>vertical Git show --patch<CR>' },
      { "a", '<cmd>vertical Git add %<CR>' },
      { "c", '<cmd>vertical Git commit<CR>' },
      { "cc", '<cmd>vertical Git commit -a<CR>' },
      { "C", '<cmd>vertical Git commit --amend --no-edit<CR>' },
      { "CC", '<cmd>vertical Git commit --amend --no-edit -a<CR>' },
      { "f", '<cmd>vertical Git fetch<CR>' },
      { "F", '<cmd>vertical Git fetch --all<CR>' },
      { "p", '<cmd>vertical Git push<CR>' },
      { "P", '<cmd>vertical Git push -f<CR>' },
    }},
    { "s", '<cmd>Gitsigns toggle_signs<CR>' },
    { "q", '<cmd>bp | bd # | bn<CR>' },
    { "Q", '<cmd>wincmd q<CR>' },
    { "h", '<cmd>wincmd h<CR>' },
    { "j", '<cmd>wincmd j<CR>' },
    { "k", '<cmd>wincmd k<CR>' },
    { "l", '<cmd>wincmd l<CR>' },
    { "v", '<cmd>vsp<CR>' },
    { "V", '<cmd>split<CR>' },
    { "r", '<cmd>set number relativenumber!<CR>' },
  }},
  { "g", {
    { "d", '<cmd>lua vim.lsp.buf.definition()<CR>' },
    { "D", '<cmd>lua vim.lsp.buf.declaration()<CR>' },
    { "r", '<cmd>lua vim.lsp.buf.references()<CR>' },
    { "i", '<cmd>lua vim.lsp.buf.implementation()<CR>' },
  }},
  { "K", '<cmd>lua vim.lsp.buf.hover()<CR>' },
}
